[package]
name = "system"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]

[dependencies.rlibc]
version = "1.0"

[dependencies.abi]
path = "../abi"

[dependencies.spin]
path = "../spin"

[features]
default = []
kernel_debug = ["abi/kernel_debug"]